# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=255, verbose_name=b'Title')),
                ('slug', models.SlugField(max_length=255)),
                ('url', models.URLField(blank=True, null=True, verbose_name=b'URL alternativa')),
                ('wrap_tag', models.CharField(default=b'li', max_length=10, verbose_name=b'HTML Tag')),
                ('class_tag', models.CharField(blank=True, default=b'', max_length=100, null=True, verbose_name=b'HTML Class')),
                ('attrs_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'HTML Attrs')),
                ('is_link', models.BooleanField(default=True, verbose_name=b'Es link')),
                ('link_target', models.CharField(blank=True, choices=[(None, 'Nothing'), (b'_blank', 'New tab'), (b'_new', 'New window')], max_length=40, null=True, verbose_name=b'Open Mode')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=1, null=True, verbose_name=b'Sort Order')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('wrap_tag', models.CharField(default=b'ul', max_length=255, verbose_name=b'HTML Tag')),
                ('class_tag', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'HTML Class')),
                ('attrs_tag', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'HTML Attrs')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menubuilder.Menu'),
        ),
    ]
